# Site settings
title: "Danilo Gouveia"
description: "Danilo Gouveia Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Danilo M. Gouveia"
resume_title:                   "Technical Account Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dm.gouveia@protonmail.ch"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+55-11-98206-4744"
resume_contact_address:         "São Paulo, SP - Brazil"

resume_header_contact_info:     "São Paulo, SP - Brazil • +55-11-98206-4744 • dm.gouveia@protonmail.ch"
display_header_contact_info:    "false"

resume_header_intro: "<p>Graduated in Computer Networks, I work for at least 10 years exclusively with information technology and 5 years with AWS.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dmgouveia"
  resume_twitter_url:           "https://twitter.com/gouveia_dm"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/danilo-gouveia/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://www.cloudwise.com.br/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

plugins:
  - github-pages
  - jekyll-embed-urls

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
